### ISSUE TITLE
Build failure: missing nl.juraji.swing:javagraphics-throbber:jar:1.0

### ISSUE THREAD

**Issue by Charlweed** [Juraji/Pinterest-Downloader#4]
Trying to build, so I can perhaps solve issue #3, but I cannot yet build from command line nor Intellij:
`[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Pinterest Downloader 1.0.1
[INFO] ------------------------------------------------------------------------
Downloading: file://C:\Users\dev\projects\3rd_party\Pinterest-Downloader/mvn-local/nl/juraji/swing/javagraphics-throbber/1.0/javagraphics-throbber-1.0.pom
Downloading: https://repo.maven.apache.org/maven2/nl/juraji/swing/javagraphics-throbber/1.0/javagraphics-throbber-1.0.pom
[WARNING] The POM for nl.juraji.swing:javagraphics-throbber:jar:1.0 is missing, no dependency information available
Downloading: file://C:\Users\dev\projects\3rd_party\Pinterest-Downloader/mvn-local/nl/juraji/swing/javagraphics-throbber/1.0/javagraphics-throbber-1.0.jar
Downloading: https://repo.maven.apache.org/maven2/nl/juraji/swing/javagraphics-throbber/1.0/javagraphics-throbber-1.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.658 s
[INFO] Finished at: 2018-04-18T10:25:41-07:00
[INFO] Final Memory: 12M/150M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project pinterest-downloader: Could not resolve dependencies for project nl.juraji:pinterest-downloader:jar:1.0.1: Could not find artifact nl.juraji.swing:javagraphics-throbber:jar:1.0 in mvn-local (file://C:\Users\dev\projects\3rd_party\Pinterest-Downloader/mvn-local) `

**Comment by Charlweed** [comment]
There is a typo in the version spec for javagraphics-throbber. The  version in mvn-local is "1.0.0" but the dependencies are on version "1.0"
When I changed the dependencies in pinterest-downloader.iml and pom.xml to 1.0.0,  I can build with mvn as expected.

**Comment by Juraji** [comment]
Hey @Charlweed, sorry for the late response!
I'm going to archive this project, since it doesn't work with Pinterest anymore.

If you loved this, I created a new, more advanced app: https://github.com/Juraji/image-manager-2
It supports the current Pinterest layout (Since I used it just yesterdayy to sync up my backup :D)
